name: Publish Specification
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
jobs:
  main:
    name: Publish to GitHub pages
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: bikeshed
          SOURCE: src/index.bs
          DESTINATION: protocol/index.html
